name: Tests
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v4
    - name: Construye imagen
      run: docker build --tag coordEjecu/clean_ine_data:latest --tag coordEjecu/clean_ine_data:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run coordEjecu/clean_ine_data:latest make check
    - name: Corre pruebas y evalua cobertura
      run: docker run coordEjecu/clean_ine_data:latest make tests
    - name: Corre reporte
      run: docker run -v $PWD:/workdir coordEjecu/clean_ine_data:latest make reports/diputados.pdf
    - name: Sube artefacto
      uses: actions/upload-artifact@v4
      with:
        name: diputados
        path: reports/diputados.pdf
